spring:
  datasource:
    username: admin
    #username: root
    password: yxjf2019!
    url: jdbc:mysql://139.159.185.154:3306/userconditions?characterEncoding=utf-8&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/yinxintest1?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


    tomcat:
      max-active: 20
      min-idle: 3
      initial-size: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000


mybatis-plus:
  type-aliases-package: com.yuanma.condition.entity
  #mapper-locations: classpath:/MapperXml/*.xml